### PR TITLE
Fix #23: Add compatibility layer for Plone 4.0

### LINKED ISSUE #23: Plone 4.0.9 broken after install of 1.0 (No module named uuid.interfaces)
Log:

... snip ...
  File "/var/www/plone/plone4/buildout-cache/eggs/collective.dancing-1.0-py2.6.egg/collective/dancing/browser/sendnewsletter.py", line 43, in <module>
    from plone.uuid.interfaces import IUUID
ZopeXMLConfigurationError: File "/var/www/plone/plone4/buildout-cache/eggs/Plone-4.0.9-py2.6.egg/Products/CMFPlone/configure.zcml", line 94.4-98.10
    ZopeXMLConfigurationError: File "/var/www/plone/plone4/buildout-cache/eggs/collective.dancing-1.0-py2.6.egg/collective/dancing/configure.zcml", line 20.2-20.32
    ZopeXMLConfigurationError: File "/var/www/plone/plone4/buildout-cache/eggs/collective.dancing-1.0-py2.6.egg/collective/dancing/browser/configure.zcml", line 211.2-216.7
    ImportError: No module named uuid.interfaces

### PR DESCRIPTION
**Pull request by mck9**

### CODE REVIEW

**Comment by frisi** [comment]
thanks @mck9

this looks good to me. according to @saily's commit (https://github.com/collective/collective.dancing/commit/d82ed54f628bd86f92f6cbf411a189f06986a67d) we still support plone 4.0 and have tests for it.
i wonder how tests did pass w/o this conditional import.
@saily can you please tell me if we required additional packages in the buildout that could handle this as well or if we should merge this change?

**Comment by saily** [comment]
@frisi i have no idea and no time to look into this.

**Comment by frisi** [comment]
as [archetypes.referencebrowserwidget does it the same way](https://github.com/plone/archetypes.referencebrowserwidget/commit/7f94417fa1754d1d972663657cfa019325751ce2) i'd merge this.
maybe @mck9 can look up why tests have been passing for plone4.0 w/o this change (maybe we can find and fix some test-problems here)

**Comment by frisi** [comment]
cleaning up the tracker - support for plone >4.3 has been dropped in https://github.com/collective/collective.dancing/commit/d65d0dfc40b256736202c4e22f8b800581712dce

**Pull request closed without merging**
