### PR TITLE
[WIP] content rules, send to section and external subscribers features 

### PR DESCRIPTION
**Pull request by djay**
Sorry this got merged into a one branch.

Includes 4 enhancements
1. ability to send an item as a newsletter just to one section of the list based on optional collectors
2. ability to automatically send immediately via content rules. Includes filtering via a collectors.
3. Ability to integrate with external subscriber databases.
4. Ability to export sections in CSV

There are few things left to do
- [x] make existing tests pass
- [x] add tests for new features

Further enhancements
- schedule via a content rule based on content date such as effective date. Reschedule if content further modified.
- validation of content rules to ensure timed scheduler in place
- remove ability to import and add subscribers to external subscriber channel
- add ability to list and search external subscriber channel
- validation of external subscriber script to ensure sections and optional collectors match. or just display differences
- improve descriptions on forms, including documenting external subscriber script in the UI

These features were sponsored by PretaGov.

### CODE REVIEW

**Comment by ivanteoh** [comment]
One thing we would like to highlight is ability to integrate with external subscriber databases. It accept a Python list from Python script path. The subscriber structure is 
```
{'email': u'test@mail.com',
'format': 'html',
'subscription_date': CreationDate,
'unsubscribe_url': u'https://localhost:8080/db/pgUnsubscribe?secret=34',
'my_subscriptions_url': u'https://localhost:8080/db/pgMySubscriptions?secret=34',
'topics': [u'news'],
'subscriber_data': {'organization': u'blah'}}
```
where both `format` and `subscription_date` keys will be insert into `metadata`,
list of values of `topics` key will be insert into `collector_data` and
the rest will be insert into `composer_data`.
Is that okay for you guys?

**Comment by dnouri** [comment]
@ivanteoh Looks good to me.  Wonder what others think.

**Comment by ivanteoh** [comment]
@saily Is it good to merge? We added tests for new features. Any feedback?

**Comment by saily** [comment]
This looks good to me, let's merge it!

**Pull request merged**
