### PR TITLE
export subscription metadata

### PR DESCRIPTION
**Pull request by frisi**
this adds metadata to the csv export of channel subscribers.

this allows to identify subscriptions that have not been validated (pending=True) (otherwhise ex- and importing would add users that did not confirm their subscription)

see changelog for details

(see https://github.com/collective/collective.dancing/issues/15)

### CODE REVIEW

**Comment by frisi** [comment]
@ale-rt and @cekk could you pleas review this PR too?
if ok, i'll merge and create a new release

@mauritsvanrees or @dnouri could you add me as a maintainer/owner for https://pypi.python.org/pypi/collective.dancing and https://pypi.python.org/pypi/collective.singing?
my pypi user is frisi

**Comment by ale-rt** [comment]
As I was already saying I am not so much into S&D code.
Anyway it looks like you are going this for good, so I am fine for every merge that will not break the tests!

**Comment by mck9** [comment]
We made a similar change. You can view it here:
https://github.com/tuxwerk/collective.dancing/commit/0ce097fb2adc0bfa0bf97abedecffcd3fc82968f

**Comment by frisi** [comment]
thansk for mentioning your commit @mck9 
i've added format and language too, so it covers all metadata values.
do your branches contain other fixes/features that would be interesing for all s&d users?

**Comment by mauritsvanrees** [comment]
@frisi I have added you as owner on the two packages on PyPI.
I am not using S&D anymore, so I have no opinion on the change.

**Comment by mck9** [comment]
@frisi We added an itemX_url replacement, that can be used to show a link to the newsletter on the webpage (View this email in your browser):
https://github.com/tuxwerk/collective.dancing/commit/5e841d120f868e91fa8e3fbe1cce9a49b7e6c3b2

also replaced the regex email validator with the plone email validator:
https://github.com/tuxwerk/collective.dancing/commit/c2dd861bd7a42a022ca7dbb15c32cb2d4eb30090

and made a image alignment patch for outlook:
https://github.com/tuxwerk/collective.dancing/commit/f455bda3d69fc5572820fd998b5052c01814216a

I can clean it up, make tests and pull requests if you are interested in the features.

**Comment by frisi** [comment]
@mck9 thanks for your reply. 

i think the email validator is intersting for all s&d users (including me ;-)

not sure about the image alignment. we are using custom composers/templates in our project

about the itemX_url: i don't see the usecase for this in our project (we send items found by a collector). this might be interesting if you send out one article manually as newsletter and need to include its url in the template text somewhere. it will definitely not hurt but needs some documentation i think.

**Pull request merged**
