### PR TITLE
show variable name in previews if default is none

### PR DESCRIPTION
**Pull request by frisi**
@dnouri wanna review? :-P

### CODE REVIEW

**Comment by dnouri** [comment]
@frisi LGTM ;-) What's up with the tests though.

**Comment by frisi** [comment]
jenkins test this please

**Comment by frisi** [comment]
the problem with the test occures with recent plone versions.
on my laptop i tested using my existing buildout and that worked. after re-running builout the tests failed.

- 4.3.17 broken
- 4.3.15 broken
- 4.3.10 works
- 4.3.12 broken
- 4.3.11 works

tests are only broken for PrettySubscriptionsForm.
to me it looks like the changes done in
https://github.com/collective/collective.dancing/commit/b9bc666d2697e52bd08446f0106251e3081d0e75
do not work in more recent versions of plone.app.z3cform or some z3c.form related packages.

z3c.form itself is pinned to 3.1.1 by the buildout (plone 4.3.17 would ship with 3.2.11)
when removing the pins in versions.cfg additional tests are broken.

i'd suggest to
* add a ticket for fixing tests for plone>4.3.11
* keep the pin for plone 4.3.11 in the meantime (done in this pr)
* remove plone 4.0 and 4.1 from the test matrix (done in this pr)
* maybe also remove plone 4.2 from .travis.yml

@dnouri please merge if you agree ;-)

**Comment by dnouri** [comment]
@frisi Looks good! Sadly I don't have write access to this repo or I would merge. ;-)

**Pull request merged**
